name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            deps: sudo apt-get install -y cmake libssl-dev
          - os: ubuntu-22.04-arm
            deps: sudo apt-get install -y cmake libssl-dev
          - os: windows-latest
            deps: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          - os: windows-11-arm
            deps: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: ${{ matrix.deps }}

      - name: Setup lde
        uses: lde-org/setup-lde@master
        with:
          version: nightly

      - name: Run tests
        run: lde test
