name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install -y cmake libssl-dev

      - name: Setup lde
        uses: lde-org/setup-lde@master
        with:
          version: nightly

      - name: Run tests
        run: lde test
